CREATE TABLE EMPLOYEE (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    CITY_ID INTEGER      NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CITY (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    CODE VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);